### ISSUE TITLE
Use animated smiles icons

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#10]
You can download them for example here:
https://www.behance.net/gallery/34559659/Facebook

These animated icons would be used only for "Rate window", after that we can use normal non-animated .png icons (I recommend ot use smaller icons, maybe 32-40px

**Comment by WhiteNeo** [comment]
Ok another one bites the dust, i have taken all the entire day to make the gifs :s i am so scared about this because it takes me many time, but yeah it's necesary and done :)

**Comment by Eldenroot** [comment]
Great! Looooooks really nice!
