### ISSUE TITLE
Show total reactions given/taken in member profile

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#11]
MAybe something like MyReactions has:
![da69a7de-adcc-11e6-9faa-b7bfd5288bf6](https://user-images.githubusercontent.com/778890/34320402-dd4eb7ec-e7f9-11e7-8218-e98ef3b83468.png)

**Comment by Eldenroot** [comment]
Maybe something like this would be enough (without the names of course, i didnt find better image)
https://cloud.githubusercontent.com/assets/798235/19440513/792e0b6c-9482-11e6-8410-c5522ca93fed.png

**Comment by WhiteNeo** [comment]
Ok that was nice i will review it adn try to make something interesting in profile :)

**Comment by WhiteNeo** [comment]
Ok this one was added now but it need some customizations yet, anyway now it is working and added with a recount tool of course :)
