### ISSUE TITLE
Better output for "Top rated" post on member profile

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#12]
![image](https://user-images.githubusercontent.com/778890/34320411-1dd446ce-e7fa-11e7-8879-584642923de5.png)

Just a design idea :)

**Comment by WhiteNeo** [comment]
I add only a customized var and sinlge style to all users who waste my time with the idea they use a responsive design and html 5 no tables, no bla bla bla. So i have reduced that and users can use the var inside member_profile to add whatever they want :) And the style is only an idea it can be customized, but i will work on this latter 👍

**Comment by Eldenroot** [comment]
I agree, you can add a post content, show the reactions under it and maybe add post time and date variable.

**Comment by WhiteNeo** [comment]
Yeah i work on that but i have to change all retrieved data into database to not overload the server, like actually i have done into showthread, i have worked on it all entire day so it is almost done, but this part is the next one when all have done. Either i have to remake alerts parts and more for the option only firts post or all post i think this must be the most important setting, but the other ones are already, if you leave blank field to search for days it would not work, i will add it if you set 0, i dunno if 0 actually works but empty field do the job.

And date are added into modal loads, but it is only in the firts part due i will rewrite many parts of code due i have ids for buttons and more, so i have to work on all js and code parts, but i will do that in this days :)

**Comment by WhiteNeo** [comment]
I will work on this so it is the only one open issue to work with and the new ones when i have the time to do i have thinked to release this until Dec 31 but i think i have no more free time this week so i am very bussy in next weeks and i decide to let the file here. This file is ended at this point but i will work into profile adjustments and addons :)

**Comment by WhiteNeo** [comment]
Ok this is done, i think this part must works but have to test :) Anyway i've write this part yesterday so it have to work ;)
