### ISSUE TITLE
Add support for theme variable in postbit author template

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#15]
Is possible to add a support for template variable to show:
- total reaction given
- total reaction received

which will be shown after the user avatar in the postbit? Do not add them by default, just add support so admin can add them and style them manually. This would be nice to have an info about the user how active he is.

**Comment by WhiteNeo** [comment]
Added as in profile this one is end at this point.

You can add/remove the new vars or add it new ones:

I will add it the templates and vars into readme file, thanks for the feedback @Eldenroot
