### ISSUE TITLE
Rates given/received - postbit

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#16]
![image](https://user-images.githubusercontent.com/778890/34412131-a085d33c-ebdb-11e7-9bc3-4d3742814363.png)
Click on this rate given/received

you will see:
![image](https://user-images.githubusercontent.com/778890/34412150-bbdbbba6-ebdb-11e7-8349-7dd187b73799.png)

The title should be changed to something like: Rates given (or received) for user "username". Moreover you can change the layout a little bit (by defaultú - move time and date to the right, etc.

**Comment by WhiteNeo** [comment]
Yes it takes the same template to not overload the site with unused templates, i see when there are templates called but there is nothing in the page then 1 query is taken for every template, so the best way to performance is this :)

I will customize it, but first at all i have to recode all plugin when i have fixed posible bugs and the first part is to make templates for all entire plugin :)

**Comment by WhiteNeo** [comment]
Ok this part is fixed too on new version :)

It will add the total found items fot rates given and received values must change due forum permissions, you can see the total items marked from posts you can see to not retrieve that information to guests, but if you are the owner well yeah all counters should be fine :)
