### ISSUE TITLE
Add ajax for removing votes from the post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#18]
It is really cool, thank you!

Anyway you have to refresh the page after removing, is possible to add AJAX refresh?

![image](https://user-images.githubusercontent.com/778890/34412266-775790e4-ebdc-11e7-9399-35a628e546a0.png)

**Comment by Eldenroot** [comment]
+ add jGrowl notification when you remove the post rate
+ maybe add a title with custom lang variable for this "like button" to show "Click to remove the post rating"

**Comment by WhiteNeo** [comment]
Yeah jGrowl and ajax is there when add or remove once per a time, i do not know if double instances are verified this is one of the parts of tests so i will test it to see it and improve that parts mentioned above thanks @Eldenroot

**Comment by WhiteNeo** [comment]
I let users decide what to use into lang vars :) Only i add a descriptive text to remove or add and done, you can change it to whatever on language phrases that's the purpose, but there are a cupple of errors in this part that have been fixed in this latest release, so now all have to work as is.

**Comment by Eldenroot** [comment]
OK, what about AJAX for removing?

**Comment by WhiteNeo** [comment]
Yep is added the jGrowl effect and here is the lang var for it.

https://github.com/WhiteNeo/post_rate/blob/dd61aed5d38e9a06f7aaeb124cd94d9fe64542cf/inc/languages/english/dnt_post_rate.lang.php#L27

Anyway i will add some lang changes to add as you asked for but this will be in next weekend maybe or when i have some free time to work again :)
