### ISSUE TITLE
Do not limit rating to 1 month period

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#2]
Do not limit rating to 1 month period. In my opinion, there should be an option to leave it 0 to unlimited

**Comment by WhiteNeo** [comment]
Same at the first post only is for renderize and optimize server charges into plugin, but maybe i can set it as an option. Users may decide...

**Comment by WhiteNeo** [comment]
Ok done option was added...

**Comment by Eldenroot** [comment]
Thank you, Facebook do not limit rating to 30 days period. If you wanna leave this, you can make it via settings - admin can choose time period id days (0 will be unlimited, forever)
