### ISSUE TITLE
Add converter for Thank You/Like system

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#20]
Would be really nice to add a converter for Thank You/Like system (plugin). Just converts all thank you/likes into "likes" in your plugin. However would be better to add when you finish your plugin to avoid any incompatibilities.

**Comment by WhiteNeo** [comment]
Yeah this is on the list i will make a recount of my thanks system and thankyou like, even reputation mybb system addin like and angry's as reps negative and positive (the mybb system is not for sure due it have counters on every case so maybe this can not be writen but dunno). But the thanks systems yeah will be taken on mynd to add the import or converter :)

**Comment by WhiteNeo** [comment]
This part is the next one on the list then seing the problem into convert templates but i need many tests for this and databases with real data to compare retrieved data with original data and see that the converter is working fine or make the changes for it.

**Comment by WhiteNeo** [comment]
Ok this was done in the new version :)
