### ISSUE TITLE
Highlight post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#23]
Maybe the new css class for post highlight should be added into the whole postbit. 

I use something similar in my mod Thank You/Like system, where the whole post gets a new css class when there is required amount of likes/thx. It changes the background color of the post, css is 

`.popular_post{
	border: 2px solid;
	border-radius: 3px;
	border-color: rgba(112,202,47,0.5);
	background-color: rgba(139,195,74,0.3);
}`

https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/commit/44db6044d8cb20d5ac93b852f82e299a423464a6

**Comment by WhiteNeo** [comment]
That idea was taken from my thankyou mybb system from users but yeah it was done in first release and i have removed this latest ones due is an emotion only to mark but i will add it for both cases.

Thanks for the feedback ;)
