### ISSUE TITLE
Ajax for removing reaction from post is not working

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#24]
Related: #18 

It is still not working, when you add a reaction to the post, and then click to remove -> you have to refresh the page with F5. It should be refreshed automaically over AJAX (same when you add a reaction to the post). Because of that there is no jGrowl notification.

Moreover:
- there is something wrong with your latest GitHub version, smiley (images of reactions) are not shown when you add them again you have to manually refresh the page. It was fine with v1.5

**Comment by WhiteNeo** [comment]
Yes it was an error due las update, now upload new plugin and js files, run update and try it, thanks for the feedback.

**Comment by Eldenroot** [comment]
Still not working for reaction removing... :(

**Comment by WhiteNeo** [comment]
Are you sure you have runed the update task ?

Because the only error i saw is a field name missing but in my side it works fine in all senses, do you have a chance on team viewer to see what is going on ?

**Comment by Eldenroot** [comment]
I deactivate v1.5 and uninstall. Then I copy new version from GitHub and install again... so no update task was needed (and was not displayed).

I use Google Chrome, tested in Firefox and same issue. There is no AJAX for remove button. For "Rate" post it works fine.

**Comment by WhiteNeo** [comment]
Wow i am unable to reproduce this :(

I have tested many times in the new and old repo but no way to reproduce, even in the dhared video all works fine, but i know there must be in some part some broken code.

I will work on this to try and reproduce it to fix it :)

**Comment by Eldenroot** [comment]
I do not what is wrong, I can send you my url for testing board (fresh clean installed MyBB 1.8.14 jist for testing). I will send you a PM over MyBB board.

**Comment by WhiteNeo** [comment]
Yeah that woul be nice to debug it and see what can be wrong. Thanks for your time :)

**Comment by Eldenroot** [comment]
I sent you a PM in MyBB board.

**Comment by WhiteNeo** [comment]
Yes thanks i will focus my atention on this and all other bugs for this first version to make an stable one project and from there we can work on new features and improvements :)

**Comment by WhiteNeo** [comment]
![error](https://user-images.githubusercontent.com/5620232/34591807-b4220852-f185-11e7-942f-d28514a602d7.png)

Allways i have this error in your provide page so i can not test it, but i can not reproduce this error...

**Comment by WhiteNeo** [comment]
I have added you to the github repository now you can edit directly, remove or whatever i think, so it is done for me today i can not do anything for this one.

**Comment by Eldenroot** [comment]
@WhiteNeo - thank you. I fixed the error you mentioned above, please try again. I am sorry :(

**Comment by Eldenroot** [comment]
@WhiteNeo - please, last try... 👍

**Comment by WhiteNeo** [comment]
Ok i have seen is due myalerts when not present now is fixed...

thanks for the report :)

Only upload new file plugin and test it again.

**Comment by Eldenroot** [comment]
Yes, now it works fine, thank you! ;)
