### ISSUE TITLE
Better css style for "title"

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#25]
Can we use same style as you use for userlist on mouse hover?

Something like this:
http://deividmarques.github.io/facebook-reactions-css/ (just hover on the white box, there is a text displayed above).

![image](https://user-images.githubusercontent.com/778890/34480092-b3d8423a-efaa-11e7-86d4-1b7bdd5efa3b.png)

**Comment by WhiteNeo** [comment]
It can be improved but can cause conflicts when users use Tooltip as me, so automatically it adds this, but i will se what can i do for this, thanks.

**Comment by WhiteNeo** [comment]
This is done, in next version this changes should be in there and needs some css for sure i have added a new span class for titles to use for this and maybe others in future additions
