### ISSUE TITLE
jGrowl - missing translations

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#26]
Only lang string is displayed (top right corner), not the language phrases from .lang file

![image](https://user-images.githubusercontent.com/778890/34480132-f4ba0310-efaa-11e7-9530-8bf1079e38c4.png)

**Comment by WhiteNeo** [comment]
Yes all js have some issues due template improvements so now i was fixed in this release, ajax must works, even remove lang popup was missing in past version, this new version fix this parts :)

**Comment by Eldenroot** [comment]
Now works fine, thank you!
