### ISSUE TITLE
"View All" returns 404 error (postbit)

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#27]
Add a new reaction (do not refresh the page) to the post and click to "View All" -> 404 error is showed. 

Anyway when you refresh the page and then click to "View All" -> works fine.

**Comment by WhiteNeo** [comment]
Yeah it was a bug due templates so i was rewritted that parts, now it have to works fine, all ajax i mean :)

**Comment by Eldenroot** [comment]
Works fine, thank you!
