### ISSUE TITLE
Missing smiley name in "dnd_post_rate.php" page

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#28]
![image](https://user-images.githubusercontent.com/778890/34480229-66370e48-efab-11e7-9948-f3648c413019.png)

In v1.5 there was a name and icon of the smiley displayed

**Comment by WhiteNeo** [comment]
I will revie this, thanks for the feedback ;)

**Comment by WhiteNeo** [comment]
Fixed. Test it and let me know.

**Comment by Eldenroot** [comment]
Yes, it works fine in the new version, anyway it needs some CSS styling.
![image](https://user-images.githubusercontent.com/778890/34493415-0db53164-efec-11e7-8241-e2f52b20dc1a.png)

- add padding for user avatar
- better position for "icon"
- remove cursor: pointer for icons
