### ISSUE TITLE
"View All" returns 404 error (member profile) + not showing the post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#29]
![image](https://user-images.githubusercontent.com/778890/34480296-cf113a38-efab-11e7-9a91-10018d2f544c.png)

Click to the "View All" in member profile page -> you will get 404 error, link is broken.

Moreover, can you please add:
- name of the thread/post and a link to that thread/post
- date and time when was post/thread posted
- maybe a small part of the message (first 120 symbols?),

**Comment by WhiteNeo** [comment]
Yes it was an issue due templates improving, so now have to works :)

About thread subject it can not be done because some posts are not hidden and this part would not take forum permissions, only shows thread subject to not provide any other information unnecesary in here :)

**Comment by Eldenroot** [comment]
Is possible to add a link to that post at least? Now users dont know which post is the most rated :(

**Comment by WhiteNeo** [comment]
Yes that was added in member profile

https://imgur.com/WwiNewR
