### ISSUE TITLE
Show list of users who rated the post in a modal

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#3]
Show list of users who rated the post in a modal

- show time and date
- show username
- show what the user added

**Comment by WhiteNeo** [comment]
I think this was taken in thread hover of every image but only latest 10 usernames into a popup, maybe it can be done via modals, but nobody likes modals :( only me and others, ha ha ha. I have added by ajax requests on mouse over and prevent to reload twice :)

**Comment by WhiteNeo** [comment]
Yes now i have added the limit of user in the list into an admicp option, but i think this works better this way, single, quick and without security risks.

**Comment by Eldenroot** [comment]
In my opinion user wanna know who added reaction to the post and when... it is a easy way how to see a feedback from community. Anyway, it is a small feature :) 

The popup shown on mouse hover is not working properly, it is misaligned sometime (Google Chrome), I will try to debug. (I will let you know in 2 days, I will be without internet access until 26th december)

**Comment by WhiteNeo** [comment]
Nice addon bro thanks for the feedback this was added in this new version :)
