### ISSUE TITLE
Show a notice or hide top rated post box in member profile if doesnt exist

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#33]
As title says - this box should be invisible when there is no post rated for that user

![image](https://user-images.githubusercontent.com/778890/34493605-fbd080ba-efec-11e7-9b9e-0f1419531fcf.png)

**Comment by WhiteNeo** [comment]
With the new addon i think this does not happens, it is related to this issue:

https://github.com/WhiteNeo/post_rate/issues/34
