### ISSUE TITLE
Best rated thread should be best rated post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#34]
Actually it should show only user's post rating, not take the all reactions from all the post in the thread.

Let me describe this issue:
User "1" create a new thread but dont get any reactions for his first post -> user "2" reply in this thread and his post will get 10 reactions -> check the member profile of user 1 -> you will see top rated thread for this user but actually his post doesnt get any reaction, 

So we should change this to "TOP RATED POST"

**Comment by WhiteNeo** [comment]
Yes this was taken in mind thanks for this contribution, now i have added 2 instances of code, to load best thread or post if the case is one or another. That was due the last improvement to show all content in thread list :) That was the reason sometimes i do not want touche this parts of code due several bugs must be happen, hahaha. Anyway it must be fixed now :)
