### ISSUE TITLE
Add a new lang variable for error notice when the user doesnt have any reaction

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#35]
Open member profile page or post bit -> click on the link (number) for reactions given or received. When the user has "0" reactions given or received and you click on that, you will see this error notice:
![image](https://user-images.githubusercontent.com/778890/34493832-ef86d380-efed-11e7-96b5-a3d7dafe0714.png)

and error notice:
![image](https://user-images.githubusercontent.com/778890/34493873-2642d8f6-efee-11e7-915e-d3b3f87dc3ea.png)

So, you should add new language string -> something like: 
"This user hasn't received/given any reactions yet"

+ change a title - change "Post rate error" to something like: Reaction given/received

**Comment by WhiteNeo** [comment]
I have removed to only no rates this way all posts, threads, given, received and more takes in mind due templates improve, to not create new ones for every case or new lang additions due i think this way is more than enought for now, but we can add it a new lang var for every case like titles :) In that same parts, but the most important thing now is that the plugin works fine :)

**Comment by Eldenroot** [comment]
Yea, it is a beta version so I am posting my ideas and feature request how to make this plugin perfect when will be released as a stable version.

**Comment by WhiteNeo** [comment]
Yes all was taken in mind as you can see :)

But the most important is an stable version then this stuff would be easy and takes only a pair of minutes to add, remove, modify. Anyway i will work on this asap

**Comment by WhiteNeo** [comment]
Language variables added. Now we have to test all is fine :)
