### ISSUE TITLE
Change URL for "Top rated post" in member profile

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#36]
Now after clicking to the thread name in the user profile -> it redirects to the thread -> anyway it should redirects to the rated post.

Now it uses this:
http://www.testingpage.4fan.cz/showthread.php?tid=2

It should be changed to this (use #pid)
http://www.testingpage.4fan.cz/showthread.php?tid=2&pid=4#pid4

**Comment by Eldenroot** [comment]
@WhiteNeo - you have a typo in your code:

You added this:
`http://www.testingpage.4fan.cz/showthread.php?tid=2#pid4&pid=4`
Anyway it is not working, correct output is:
`http://www.testingpage.4fan.cz/showthread.php?tid=2&pid=4#pid4`
  
The affected line is:
https://github.com/WhiteNeo/post_rate/commit/e3b560ea6a727d5ba8370e1dd5265c81cb22244a#diff-0c25ed67b912dd8f98b414ec22e9aa12R2166

**Comment by Eldenroot** [comment]
Works fine with your last fix, thx!

**Comment by WhiteNeo** [comment]
It was a typo error inside the code, no problem :)
