### ISSUE TITLE
Allow to change/remove the post rating, highlight the user choose

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#4]
Allow to change/remove the post rating, highlight the user choose who the user added to the post.

**Comment by Eldenroot** [comment]
For the highlight idea - maybe we can add a new css class for the smiley image and add something like this for css class emoji_selected

`   border: 1px solid #ddd;
    border-radius: 50%;
    box-shadow: 0 0 1px 1px #166f16;`

![image](https://user-images.githubusercontent.com/778890/34322951-9ffacbba-e835-11e7-8bec-01195df7fc99.png)

Just an idea, it needs more discuss

**Comment by WhiteNeo** [comment]
Ah i understand do you like to add it into only the most used reactions only :)

I have thinked in all entire post :) but yes it can be added :)

I need to think about it because it has some query's that have been changed into database like save information serialized to get it again, right now is only a plain text and content into db, but maybe the best option is to use serialized content to get the data or retrieve it with lesser charges and more quick :)

**Comment by WhiteNeo** [comment]
ABout change or removal i was thinked in that for that reason every 30 days you can choose a new emotion for the post, counter was recorded, but data updated into db to not save more data than needed, i have thinked in all posible aspects of this mod to do the most lightweight and usefull mod :)

**Comment by Eldenroot** [comment]
OK, then this should be added as a new option OR do not allow choose a new emotion icon after 30 days period. Why 30 days period?! Admin should have an option for that in ACP - set time period in days for removing/changing the emotion

**Comment by Eldenroot** [comment]
OK, I have an idea how to show user's choose - we can use same way how Facebook does. When you select the reaction, the selected smiley is shown in a button. So we can replace the "Rate" button with a new button with smiley and text inside? Moreover you can add another feature - remove emotion/change it -> just click on that button and you are done.

![image](https://user-images.githubusercontent.com/778890/34325049-9b8334e0-e886-11e7-841d-c0772ea97196.png)

**Comment by WhiteNeo** [comment]
Ok done one more hit for the Neo :)
