### ISSUE TITLE
Split settings - Limit to search userlist

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#41]
Is possible to split this setting - now it applies for both - threadlist and for posts together. Is possible to add a separated setting for posts and for threadlist? 

![image](https://user-images.githubusercontent.com/778890/34578707-4473c5ee-f186-11e7-925d-ddc1fca656ac.png)

**Comment by WhiteNeo** [comment]
It takes the same because post / threadlist is the same as first post so it is the same at the end and unnecessary duplicated entry don't you think ?

**Comment by Eldenroot** [comment]
It depends... I prefer clean and simple look for threadlist and detailed info for posts... now we have detailed info for both places. It is up to you :) just idea

**Comment by WhiteNeo** [comment]
And what about remove that part in here ?

It saves a query as you have asked in first issue, i think in here only reactions used and without qty. Because there is no point at all for it but i dunno :)

**Comment by Eldenroot** [comment]
In threadlist: show reactions with quantity (numbersú but without userlist on mouse hover (we dont really need to show users in threadlist). We can save one query from DB. For post part - leave it as it is now.

**Comment by WhiteNeo** [comment]
+1 i think is not necesary because in posts all information must be retrieved.

I will remove onclick events too only the icon and number of reactions must be enought :)

**Comment by Eldenroot** [comment]
Yes, agree - one saved query :)

> I will remove onclick events too only the icon and number of reactions must be enought :)
Yes, for threadlist it is enough ;) - or maybe leave onclick event? Does it need an extra query?

**Comment by WhiteNeo** [comment]
Ok this is done :)

**Comment by Eldenroot** [comment]
Works fine, good job!
