### ISSUE TITLE
"View All" - change to show all rates given to the post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#43]
"View All" - maybe change to show all rates given to the post, not for the all posts in that thread?

![image](https://user-images.githubusercontent.com/778890/34579053-b7dacf68-f187-11e7-816d-318b75ef0711.png)

Just a small idea - for me it is not clear (and some users wrote me that it is confusing) - it should show all emojis given in the post, but is shows all emojis given in the thread (yes, it is supposed to be like that). I am not sure about it, but I like it. Maybe can we leave this "variable" available and move it this "View all" to somewhere else? What about here (it would be available in from the post and from the thread list, same template)

![image](https://user-images.githubusercontent.com/778890/34579190-3dab3c5e-f188-11e7-8564-6996a134bfed.png)

**Comment by WhiteNeo** [comment]
Yes i think this way is better but it is caused due the all posts improvement hahaha.

I will remove all in thread there is no case for that due users only want to see all posts reaction not all in thread i think that, but what do you think about entire change and remove this search for entire thread ? Besides post is fine due new changes.

**Comment by WhiteNeo** [comment]
Now it takes by an option selected, but i think have to work fine now :)

**Comment by Eldenroot** [comment]
Should be fine, thx!
