### ISSUE TITLE
Different output in Firefox/Google Chrome

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#44]
Firefox:
![image](https://user-images.githubusercontent.com/778890/34621278-d2d2fe5a-f248-11e7-9cf4-faac6267deb0.png)

Google Chrome/Opera
![image](https://user-images.githubusercontent.com/778890/34621290-dea3953c-f248-11e7-8d16-00867abc2941.png)

margin-top: -10px is the issue

**Comment by WhiteNeo** [comment]
In my versions are fine i have added fix hack but have to add that other parts :)

**Comment by Eldenroot** [comment]
Fixed, thank you!
