### ISSUE TITLE
Change settings/add a new one: Select usergroups who can use emojis in posts

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#45]
This settings is fine but it should be replaced by this:

"Select usergroups who can rate posts"

All usergroups will see emojis given to the posts but only selected can add emojis.

Why this setting? For example I dont wanna enable rating posts by Guest and specific usergroups (unregistered, inactivated, banned) but I wanna display rates to them.

**Comment by WhiteNeo** [comment]
Is not posible in this versio due permissions for seo rules if you show and hide contents for some parts may lose points.

I see the right way is to use it or not the plugin but future version prevents that or dunno we have to analize

**Comment by Eldenroot** [comment]
OK, so how to disable rating button for guests for example? They should see the rating but cannot add

**Comment by WhiteNeo** [comment]
Actually is not posible but it can be changed into post hook removing usergroup permissions.

That way solve the issue but again whe they see contents or try to add some queries have to run for reviewal purposes.

All parts are covered, so remove permissions lines in potbit and you will get results but other errors would appear due that permissions.

**Comment by Eldenroot** [comment]
This should be taken in mind and somehow by added in next release.

**Comment by WhiteNeo** [comment]
Ok it is done i have removed user premissions to let the users see all contents, but users in the list of groups only can rate posts, other users only can see the contents.

Let me know, because i have worked in this :) but not for sure if all goes fine i think so, anyway i have to work more in other parts i think.

**Comment by Eldenroot** [comment]
Works fine, thank you, great addition!
