### ISSUE TITLE
Issue with new styled "titles" on mouse hover + improvements

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#47]
I really like the new style for titles tag. Anyway there is a small issue when you disable (set 0) in ACP settings: 
![image](https://user-images.githubusercontent.com/778890/34649301-cafbbeaa-f3ac-11e7-949e-245bd8d1dda8.png)

After that, the title is not displayed correctly
![image](https://user-images.githubusercontent.com/778890/34649306-daf26890-f3ac-11e7-9272-734e07620870.png)
![image](https://user-images.githubusercontent.com/778890/34649308-e3d0d956-f3ac-11e7-8c2c-80751a5b72b2.png)

Moreover, some more ideas:
- make name of the emoji (Like, Love, ...) bolded 
- show and X mores italic

what do you think?

**Comment by WhiteNeo** [comment]
It is bolded, ha ha ha but maybe can not see it at all i add string tags, yeah it is fine i will add this, but it works fine ? I think so but i want to be sure of that :)

**Comment by WhiteNeo** [comment]
Ok this is done :) I have changes template of that part and lang vars, and some plugin parts so update files and let me know.

**Comment by Eldenroot** [comment]
Hmm, ok, but make bolded only the name of the reactions... the usernames should be "normal" non-bolded.

**Comment by WhiteNeo** [comment]
Usernames are normal, or at least it suposes to do, ha ha ha.

I do not remember taht parts only i work on title and the latest italic. But i will review this thanks.

**Comment by WhiteNeo** [comment]
Nope there are no bold style or code into usernames or dates, only plain text, maybe is taken directly from mybb  style i will analize it, but is strange...

**Comment by Eldenroot** [comment]
Hmm, strange, all text uses bold style on mouse hover. Maybe some css issue?

**Comment by WhiteNeo** [comment]
I foun the issue is taken from the div box, so i have changed that and now it is working fine 👍
