### ISSUE TITLE
CSS styling - would be nice to improve css styling before final release

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#50]
There are a lot of missing spaces and ; in css, I wil make a PR

**Comment by WhiteNeo** [comment]
Ok it is in your hands now :)

I will back into it latter i will go to eat now.

Thanks for all, this must be an awesome plugin :)

**Comment by Eldenroot** [comment]
Fixed, should be fine, please review changes in your free time :)
