### ISSUE TITLE
MariaDB mariadb  reserved words

### ISSUE THREAD

**Issue by insert-mx** [WhiteNeo/post_rate#51]
Install fails in MariaDB 10.2.

"Row" word is  reserved for MariaDB 10.2

**Comment by WhiteNeo** [comment]
Ok the first to solve i will review it asap

Thanks for the feedback

It is strange i have Maria DB 10.2.8 and no issues i have written with this motor and php 7.2, SQL 5.7.20 and apache 2.4.29.

Any other sugestion due i use rows words when retrieve some matches but not at all, only mysql mybb db instances with row word.

What line ? To debug it if it is posible.
 
Ok i have rewritten the only one part where rows are used, work Row and row was never used into the plugin, but rows only once, so i have removed and now have to work without problem, but for me it works fine in Maria DB 10.2.8 as i said before :O
