### ISSUE TITLE
Change order of emojis 

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#53]
Can you please change order of emojis in "Rate post" to follow Facebook style.

![image](https://user-images.githubusercontent.com/778890/34689670-a84054e2-f4b6-11e7-808f-f41557818b10.png)

Change position of "Smiley" with "Wow". Thank you :)

**Comment by WhiteNeo** [comment]
It is taken for rep conversion as is suposing more than 1 for love, 1 for like, neutral or 0 wow, negative or -1 smile and -2 for angry only cry was not taken but it is the order we can use into mybb i think for easy reference

**Comment by WhiteNeo** [comment]
Ok this can be done into templates easily, only change order of images code of images whenever you want and that was all, to not loose actual data due many users have it already in their forums and do not wanna change (loose) retrieved data.
