### ISSUE TITLE
Final version

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#54]
Hi @WhiteNeo , I have a question - I would like to use this plugin on my live board with over 1k users. It will replace my Thank you/Like system. Is it safe? Or should I wait few more days/weeks for stable release? 

Anything else planned? New features? Code clean up?

Thank you!

**Comment by WhiteNeo** [comment]
Yes it is secure due all queries are passed by escaped or secure vals when are called or inserted but i will review it to be sure at all this weekend if i can.

**Comment by WhiteNeo** [comment]
Ok i have reviewed and it is safe, at least i have it into my forums running actually, so i think with the code there is no problem at all, but if some one can found some posible case let me know to review it and fix it if require.

And thanks to all i think new 1.6.4 version is ready to use and working, now you can use templates as you like i have tested so only if you have old version deactivate, activate and on clean install works fine.

If older version then upgrade routines are needed to run until upgrade dissapear to make it up to date, finally you have to run a recount.
