### ISSUE TITLE
Change "You" to username

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#57]
Now it shows "You" in ratings... would be better to show username (at least for translation)

**Comment by WhiteNeo** [comment]
Yes i will do that due translation is better to use username :)

**Comment by WhiteNeo** [comment]
Ok this is done too i will prepare for 1.6.4 version i will review either sql sentences to be sure it is secure to use it in live boards, anyway i have it installed into my site and do not have any posible sql injection or errors but i will review it to be sure, i think all is covered but i will verify this weekend.

**Comment by Eldenroot** [comment]
OK, thank you. Would be nice to clean up a code before final release :)
