### ISSUE TITLE
SQL error in converter

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#60]
![image](https://user-images.githubusercontent.com/778890/34827246-cd2a0d32-f6d9-11e7-86c7-319c9ca61489.png)

I ran converter.php, I wanted to convert Thank You/like system into Post rates... without success

@WhiteNeo

**Comment by WhiteNeo** [comment]
it is weird due there aren't trigered values to convert.

are you sure you have read instructions ?

Because i have converted from that system without problems you have to be
sure prefix is the same anyway.

**Comment by Eldenroot** [comment]
I cannot convert likes/thx, so what to do? _(

Yes, I have read :)

**Comment by WhiteNeo** [comment]
Your database is not taken data or data was empty from that message provided, so what to convert then ?

I have runed with some tyl, thanks and thankyou mybb system data into my db, the only one that have troubles are simple likes, but now is tested and works fine, reputation of mybb either works fine.

I assume there are some kindda error into your server side.

I can not do anything at this moment due i have no idea why or how that error appears, because in my server side all goes fine.

What is the process you run to use converter anyway ?

**Comment by Eldenroot** [comment]
I turned off my board... I am logged in as an admin; cpied converter.php into my root folder; run myforum/converter.php and then it shows this error

**Comment by Eldenroot** [comment]
I can send you sql with thankyoulike data, write me your email address

**Comment by WhiteNeo** [comment]
That is not the process mentiones into readme.

You have to install post rate first at all. And have some data with your
actual system, this case tyl.

Then upload file into forum root, login as admin.

Is not necesary turn off your boards due only mods can run it.

Run this tool.

Then verify data and remove this converter file

Run Recount tool and done. Maybe you miss some of this steps.

2018-01-11 7:50 GMT-06:00 Eldenroot <notifications@github.com>:

**Comment by Eldenroot** [comment]
I did it exactly how you mentioned above... there must be a syntax error in the code :(

EDIT: my TYL system has over 10k thank you, so it should be an issue

**Comment by WhiteNeo** [comment]
I don.t think so bro because error shows that empty rows are trying to insert so in that case there are some break part inside query but i have tested before and converter goes fine if all is fine of course.

Any chance to go team viewer, data is not needed due i can not do anything with that data due all data are different from mine, with only 3 users and 10 posts only so i can not do anything with partial data, but if i see the error can retrieve what is going on.

**Comment by Eldenroot** [comment]
sure, I can provide you teamviewer conection

**Comment by Eldenroot** [comment]
Do you have discord?

**Comment by WhiteNeo** [comment]
No i don't have discord or any msn account only gmail with hangouts by
google with mozilla and gmail open.

My mail is neogeoman@gmail.com

by the way is the only contact form i have right now :)

2018-01-11 8:04 GMT-06:00 Eldenroot <notifications@github.com>:

**Comment by WhiteNeo** [comment]
Well i have to review this to see what can be the problem in here, but the solution was write a new converter for only thankyoulike, but i will review this asap.

Thanks for all your time  @Eldenroot this is very weird but we need to repair this anyway :)

**Comment by Eldenroot** [comment]
`<?php
/**
  * Autor: Dark Neo
 * Plugin: Post Rate
 * Versión: 1.6
 * Single Converter
 */
define("IN_MYBB", 1);
define("NO_ONLINE", 1);
define('DNTPRT_CONVERSION_SCRIPT','converter.php');
require_once "global.php";
require_once "./inc/init.php";
if(!$mybb->usergroup['cancp'])
    error('You have no permissions to do this task','Post Rate Error');
ini_set('max_execution_time', 300);
$batch = 0;
$total = 0;
$thx = array();
echo "Tyl converter<br />";
if($db->table_exists('g33k_thankyoulike_thankyoulike_back') && $db->table_exists('dnt_post_rate'))
{
	$db->query("TRUNCATE TABLE ".TABLE_PREFIX."dnt_post_rate");		
	$query = $db->simple_select('g33k_thankyoulike_thankyoulike_back', '*');
	while ($thanks = $db->fetch_array($query)) 
	{		
		$thx[] = array(
			'dnt_prt_type'		=> 1,			
			'dnt_prt_tid'		=> (int) $thanks['tlid'],
			'dnt_prt_pid'	 	=> (int) $thanks['pid'],
			'dnt_prt_sender'	=> (int) $thanks['uid'],
			'dnt_prt_user'		=> (int) $thanks['puid'],
			'dnt_prt_date'		=> (int) $thanks['dateline'],
			'dnt_prt_count'		=> 1
		);
		$batch++;
		$total++;
		if($batch == 1000 && is_array($thx)) {
			$db->insert_query_multiple("dnt_post_rate", $thx, "AND");
			$thx = array();
			$batch = 0;
			echo "System has converted {$total} items from TYL to Post Rate<br/>";
		}
	}
	if(is_array($thx))
	{
	$db->insert_query_multiple("dnt_post_rate", $thx, "AND");
	echo "<span style=\"color: green;\">Done!!!</span><br />System has converted {$total} items from TYL to Post Rate<br/>Remember to remove this file (converter.php) from your server...<br />Make a recount of post rates to retrieve all necessary data into your new dnt_post_rate database<br />Now you can remove / Uninstall ThankYou Like System from your board if you wish, but keep a backup of g33k_thankyoulike_thankyoulike table if you wish to revert this process";
	}
	else
		echo 'Error: '.$thx;
}`

**Comment by WhiteNeo** [comment]
Added converters for every case you must run your own converter if converter.php does not work.
