### ISSUE TITLE
"View All" does work only for the first post; for 2nd and others not

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#63]
"View All" does work only for the first post; for 2nd and others not

![image](https://user-images.githubusercontent.com/778890/34837850-61ede052-f6fc-11e7-8b47-a3c4d9ac7d94.png)

When you click to "View all" in the 2nd or 3rd etc post - it will display rates given to the first post, not for the specified post /2nd or 3rd/.

**Comment by WhiteNeo** [comment]
Ok i have written a patch for this i think must work but test it and let me know.

If do not we have to change lang var into post var, it is an issue with mybb....

**Comment by Eldenroot** [comment]
@WhiteNeo - thx, I will try tommorow (going to sleep right now, thx!)

**Comment by WhiteNeo** [comment]
thank to you take a good rest bro i keep an eye into this and other opened
issues when i was finished some pendants at home :)

**Comment by Eldenroot** [comment]
Still not working correctly... View all from the 2nd post shows only emojis from the first post of the thread.

**Comment by WhiteNeo** [comment]
Fixed...
