### ISSUE TITLE
Two settings groups are created in ACP

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#64]
![image](https://user-images.githubusercontent.com/778890/34837981-c5c15668-f6fc-11e7-92e6-aced717b2b7b.png)

**Comment by WhiteNeo** [comment]
this is caused when deactivate routine and activate do not finish so i think deactivate and activate should fix this.

**Comment by Eldenroot** [comment]
It happens on my test board too, maybe any redundant code in plugin file? If not, I will try again

**Comment by WhiteNeo** [comment]
i think is a posible bug let me verify it tomorrow at first hours.

if i have some free time latter will check it out but for sure i think
tomorrow for sure :)

**Comment by WhiteNeo** [comment]
Fixed...
